export { default as Login } from './pages/login/Login'
export { default as Signup } from './pages/signup/Signup'
export { default as Home } from './pages/home/Home'
export { default as NotFound } from './pages/page-not-found/PageNotFound'
export { default as History } from './pages/history/History'
